### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by paldeim** [analysiscenter/radio#21]
I am using the same code as in the Radio description. (I replaced the paths of course)
I tried to import dicom files, when I run the pipeline I got the exception below.
Can you help me what did i do wrong?
(python 3.6.3, Radio 0.1.0, dataset 0.3.0)

from radio import CTImagesBatch
from radio.dataset import FilesIndex, Dataset
dicom_ix = FilesIndex(path='path/to/dicom/*', no_ext=True)        
dicom_dataset = Dataset(index=dicom_ix, batch_class=CTImagesBatch)
pipeline = (
    dicom_dataset.p
    .load(fmt='dicom')
    .resize(shape=(128, 256, 256))
    .normalize_hu()
    .dump('/path/to/preprocessed/scans/')
)

pipeline.run(batch_size=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/pipeline.py", line 1088, in run
    for _ in self.gen_batch(*args, **kwargs):
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/pipeline.py", line 1035, in gen_batch
    batch_res = self._exec(batch)
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/pipeline.py", line 579, in _exec
    batch_res = self._exec_all_actions(batch)
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/pipeline.py", line 565, in _exec_all_actions
    batch = self._exec_one_action(batch, _action, _action_args, _action['kwargs'])
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/pipeline.py", line 516, in _exec_one_action
    batch = action_method(*args, **kwargs)
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/decorators.py", line 37, in _action_wrapper
    _res = action_method(action_self, *args, **kwargs)
  File "/home/cloudera/Downloads/radio-0.1.0/radio/preprocessing/ct_batch.py", line 354, in load
    self._load_dicom()              # pylint: disable=no-value-for-parameter
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/decorators.py", line 238, in wrapped_method
    return wrap_with_threads(self, args, kwargs)
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/decorators.py", line 171, in wrap_with_threads
    return _call_post_fn(self, post_fn, futures, args, full_kwargs)
  File "/home/cloudera/Downloads/radio-0.1.0/radio/dataset/dataset/decorators.py", line 136, in _call_post_fn
    return post_fn(all_results, *args, **kwargs)
  File "/home/cloudera/Downloads/radio-0.1.0/radio/preprocessing/ct_batch.py", line 804, in _post_default
    self._reraise_worker_exceptions(list_of_arrs)
  File "/home/cloudera/Downloads/radio-0.1.0/radio/preprocessing/ct_batch.py", line 780, in _reraise_worker_exceptions
    raise RuntimeError("Failed parallelizing. Some of the workers failed with following errors: ", all_errors)
RuntimeError: ('Failed parallelizing. Some of the workers failed with following errors: ', [NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory'), NotADirectoryError(20, 'Not a directory')])

**Comment by paldeim** [comment]
No problem with this, my bad.

**Comment by paldeim** [comment]
This line was the problem:
dicom_ix = FilesIndex(path='path/to/dicom/*', no_ext=True)
I changed it:
dicom_ix = FilesIndex(path='path/to/dicom/*', **dirs=True**)

**Comment by akoryagin** [comment]
Hello, @paldeim !

True, the line should go as
`dicom_ix = FilesIndex(path='path/to/dicom/*', dirs=True)`.
Thanks for highlighting the issue! We will add your fix into the next release of `RadIO`.

Best,
Alex.
