### ISSUE TITLE
No module named 'blosc.blosc_extension

### ISSUE THREAD

**Issue by sirinferhat** [analysiscenter/radio#35]
I created an environment (radIOenv) in Anaconda. And I typed python -m pip install git+https://github.com/analysiscenter/radio.git.

When i type import radio or from radio import CTImagesBatch I get the following error : ModuleNotFoundError: No module named 'blosc.blosc_extension'

>>>import radio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Anaconda3\envs\radioenv\lib\site-packages\radio\__init__.py", line 5, in <module>
    from .preprocessing import *
  File "C:\Users\user\Anaconda3\envs\radioenv\lib\site-packages\radio\preprocessing\__init__.py", line 3, in <module>
from .ct_batch import CTImagesBatch
  File "C:\Users\user\Anaconda3\envs\radioenv\lib\site-packages\radio\preprocessing\ct_batch.py", line 15, in <module>
    import blosc
  File "C:\Users\user\Anaconda3\envs\radioenv\lib\site-packages\blosc\__init__.py", line 13, in <module>
    from blosc.blosc_extension import (
ModuleNotFoundError: No module named 'blosc.blosc_extension'

**Comment by robbmcleod** [comment]
Tends to indicate that you tried to install `blosc` but it failed to compile the C-extension. Likely you do not have Microsoft Visual Studio build tools installed. They are free to download and use.

Alternatively, you can uninstall blosc (probably `pip uninstall blosc`) and then install the compiled binary via `conda install blosc python-blosc`.
