### ISSUE TITLE
ValueError('image has wrong mode',)

### ISSUE THREAD

**Issue by Screenium** [analysiscenter/radio#9]
Hi, so I am trying the same code from the tutorial on different platforms. On ubuntu 16 the first lines of code runs super fast compared to windows or mac but got different error:
```
Traceback (most recent call last):
  File "/home/~/Documents/work/radio/testRADIO.py", line 47, in <module>
    (lunaset.train >> crop_pipeline).run()
  File "/home/~/Documents/work/radio/radio/dataset/dataset/pipeline.py", line 1088, in run
    for _ in self.gen_batch(*args, **kwargs):
  File "/home/~/Documents/work/radio/radio/dataset/dataset/pipeline.py", line 1035, in gen_batch
    batch_res = self._exec(batch)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/pipeline.py", line 579, in _exec
    batch_res = self._exec_all_actions(batch)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/pipeline.py", line 565, in _exec_all_actions
    batch = self._exec_one_action(batch, _action, _action_args, _action['kwargs'])
  File "/home/~/Documents/work/radio/radio/dataset/dataset/pipeline.py", line 516, in _exec_one_action
    batch = action_method(*args, **kwargs)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/decorators.py", line 37, in _action_wrapper
    _res = action_method(action_self, *args, **kwargs)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/decorators.py", line 238, in wrapped_method
    return wrap_with_threads(self, args, kwargs)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/decorators.py", line 171, in wrap_with_threads
    return _call_post_fn(self, post_fn, futures, args, full_kwargs)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/decorators.py", line 136, in _call_post_fn
    return post_fn(all_results, *args, **kwargs)
  File "/home/~/Documents/work/radio/radio/preprocessing/ct_masked_batch.py", line 887, in _post_rebuild
    batch = super()._post_rebuild(all_outputs, new_batch, **kwargs)
  File "/home/~/Documents/work/radio/radio/preprocessing/ct_batch.py", line 962, in _post_rebuild
    self._reraise_worker_exceptions(all_outputs)
  File "/home/~/Documents/work/radio/radio/preprocessing/ct_batch.py", line 785, in _reraise_worker_exceptions
    raise RuntimeError("Failed parallelizing. Some of the workers failed with following errors: ", all_errors)
RuntimeError: ('Failed parallelizing. Some of the workers failed with following errors: ', [ValueError('image has wrong mode',), ValueError('image has wrong mode',), ValueError('image has wrong mode',), ValueError('image has wrong mode',), ValueError('image has wrong mode',), ValueError('image has wrong mode',), ValueError('image has wrong mode',)])

```

**Comment by Screenium** [comment]
After changing the resizing method to 'scipy' it has overcome the error above but raised the same error as in issue #7 (this run was done on Ubuntu): 

```
Traceback (most recent call last):
  File "/home/~/Documents/work/radio/testRADIO.py", line 84, in <module>
    batch = combine_pipeline.next_batch()
  File "/home/~/Documents/work/radio/radio/dataset/dataset/pipeline.py", line 1057, in next_batch
    batch_res = self.next_batch(*self._lazy_run[0], **self._lazy_run[1])
  File "/home/~/Documents/work/radio/radio/dataset/dataset/pipeline.py", line 1062, in next_batch
    batch_res = next(self._batch_generator)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/pipeline.py", line 1033, in gen_batch
    for batch in batch_generator:
  File "/home/~/Documents/work/radio/radio/dataset/dataset/base.py", line 162, in gen_batch
    for ix_batch in self.index.gen_batch(batch_size, shuffle, n_epochs, drop_last):
  File "/home/~/Documents/work/radio/radio/dataset/dataset/dsindex.py", line 276, in gen_batch
    batch = self.next_batch(batch_size, shuffle, n_epochs, drop_last, iter_params)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/dsindex.py", line 250, in next_batch
    return self.create_batch(rest_items, pos=True)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/dsindex.py", line 292, in create_batch
    batch = self.subset_by_pos(_batch_indices)
  File "/home/~/Documents/work/radio/radio/dataset/dataset/dsindex.py", line 80, in subset_by_pos
    return self.index[pos]
TypeError: only integer scalar arrays can be converted to a scalar index

```

**Comment by roman-kh** [comment]
Closing as non-active for a long time.
Feel free to reopen if the problem persists.
